`timescale 1ns/1ps

module tb_aho_corasick;

    reg        clk         = 0;
    reg        rst_n       = 0;
    reg [7:0]  byte_in     = 0;
    reg        byte_valid  = 0;
    reg        frame_start = 0;
    reg        frame_end   = 0;

    wire        match_found;
    wire [9:0]  match_pattern_id;
    wire [15:0] match_offset;

    wire [17:0] sram_addr;
    wire [15:0] sram_data;
    wire        sram_we_n, sram_oe_n, sram_ce_n;
    assign sram_data = 16'hZZZZ;  // not exercised by this test

    aho_corasick u_dut (
        .clk              (clk),
        .rst_n            (rst_n),
        .byte_in          (byte_in),
        .byte_valid       (byte_valid),
        .frame_start      (frame_start),
        .frame_end        (frame_end),
        .match_found      (match_found),
        .match_pattern_id (match_pattern_id),
        .match_offset     (match_offset),
        .sram_addr        (sram_addr),
        .sram_data        (sram_data),
        .sram_we_n        (sram_we_n),
        .sram_oe_n        (sram_oe_n),
        .sram_ce_n        (sram_ce_n)
    );

    always #4 clk = ~clk;  // 125 MHz

    initial begin
        $dumpfile("tb_aho_corasick.vcd");
        $dumpvars(0, tb_aho_corasick);
    end

    // Load the completed DFA tables generated by build_ac_table.py
    integer i, j;
    reg [9:0] goto_flat [0:255*256-1];  // flattened temp buffer
    initial begin
        $readmemh("goto_table.hex", goto_flat);
        for (i = 0; i < 256; i = i + 1) begin
            for (j = 0; j < 256; j = j + 1) begin
                u_dut.goto_bram[i][j] = goto_flat[i*256 + j];
            end
        end
        $readmemh("output_table.hex", u_dut.output_table);
        $readmemh("output_id.hex", u_dut.output_id);
        $display("DEBUG: Table Load Complete");
    end

    task send_byte;
        input [7:0] b;
        begin
            @(posedge clk);
            byte_in    <= b;
            byte_valid <= 1;
            @(posedge clk);
            byte_valid <= 0;
        end
    endtask

    task send_string;
        input [8*32-1:0] str;   // up to 32 ASCII chars, packed
        input integer len;
        integer k;
        begin
            for (k = 0; k < len; k = k + 1) begin
                send_byte(str[8*(len-1-k) +: 8]);
            end
        end
    endtask

    initial begin
        $display("DEBUG: stimulus block started");
        rst_n = 0;
        repeat(4) @(posedge clk);
        rst_n = 1;
        repeat(2) @(posedge clk);

        // -------------------------------------------------------
        // TEST 1: exact match on "evil"
        // -------------------------------------------------------
        $display("--- TEST 1: \"evil\" ---");
        @(posedge clk); frame_start <= 1; @(posedge clk); frame_start <= 0;
        send_string("evil", 4);
        @(posedge clk); frame_end <= 1; @(posedge clk); frame_end <= 0;
        repeat(2) @(posedge clk);

        // -------------------------------------------------------
        // TEST 2: "scam" embedded mid-stream, surrounded by noise
        // -------------------------------------------------------
        $display("--- TEST 2: \"xxscamxx\" ---");
        @(posedge clk); frame_start <= 1; @(posedge clk); frame_start <= 0;
        send_string("xxscamxx", 8);
        @(posedge clk); frame_end <= 1; @(posedge clk); frame_end <= 0;
        repeat(2) @(posedge clk);

        // -------------------------------------------------------
        // TEST 3: the failure-link stress case -- "scammer"
        // This should match pattern ID 2 ("scammer") at the end,
        // NOT just match "scam" and then desync.
        // -------------------------------------------------------
        $display("--- TEST 3: \"scammer\" ---");
        @(posedge clk); frame_start <= 1; @(posedge clk); frame_start <= 0;
        send_string("scammer", 7);
        @(posedge clk); frame_end <= 1; @(posedge clk); frame_end <= 0;
        repeat(2) @(posedge clk);

        // -------------------------------------------------------
        // TEST 4: no match at all -- should never assert match_found
        // -------------------------------------------------------
        $display("--- TEST 4: \"harmless\" (expect no match) ---");
        @(posedge clk); frame_start <= 1; @(posedge clk); frame_start <= 0;
        send_string("harmless", 8);
        @(posedge clk); frame_end <= 1; @(posedge clk); frame_end <= 0;
        repeat(2) @(posedge clk);

        $display("Simulation complete.");
        $finish;
    end

    // Monitor: print every match as it happens, with pattern name
    always @(posedge clk) begin
        if (match_found) begin
            case (match_pattern_id)
                10'd0: $display("  MATCH: \"evil\" at offset %0d", match_offset);
                10'd1: $display("  MATCH: \"scam\" at offset %0d", match_offset);
                10'd2: $display("  MATCH: \"scammer\" at offset %0d", match_offset);
                10'd3: $display("  MATCH: \"bad\" at offset %0d", match_offset);
                default: $display("  MATCH: unknown id %0d at offset %0d",
                                   match_pattern_id, match_offset);
            endcase
        end
    end

endmodule